# Generated by Django 3.0.5 on 2020-12-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
